name: "Setup Deno"
description: "Setup Deno by installing, downloading, and adding it to the path."
author: "Deno Land"
branding:
  icon: "play-circle"
  color: "gray-dark"
inputs:
  deno-version:
    description: The Deno version to install. Can be a semver version of a stable release, "canary" for the latest canary, or the Git hash of a specific canary release.
    default: "1.x"
  deno-version-file:
    description: File containing the Deno version to install such as .dvmrc or .tool-versions.
outputs:
  deno-version:
    description: "The Deno version that was installed."
  is-canary:
    description: "If the installed Deno version was a canary version."
runs:
  using: "node20"
  main: "main.js"
