name: "Setup Deno"
description: "Setup Deno by installing, downloading, and adding it to the path."
author: "Deno Land"
branding:
  icon: "play-circle"
  color: "gray-dark"
inputs:
  deno-version:
    description: The Deno version to install. Can be a semver version of a stable release, "canary" for the latest canary, or the Git hash of a specific canary release.
    default: "2.x"
  deno-version-file:
    description: File containing the Deno version to install such as .dvmrc or .tool-versions.
  deno-binary-name:
    description: The name to use for the binary.
    default: "deno"
outputs:
  deno-version:
    description: "The Deno version that was installed."
  release-channel:
    description: "The release channel of the installed version."
runs:
  using: "node20"
  main: "main.mjs"
